version: '3'
services:

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: secret-user
      POSTGRES_PASSWORD: secret-password
      POSTGRES_DB: management
      POSTGRES_HOST: postgres

  management-api:
    build:
      dockerfile: Dockerfile
      context: .
    image: eliasnepo/management-api
    container_name: management-api
    ports:
      - 8080:8080
    environment:
      APP_PROFILE: local
      DB_URL: jdbc:postgresql://postgres:5432/management

volumes:
  postgres-volume: